-- MySQL Script generated by MySQL Workbench
-- mié 05 mar 2025 12:18:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id Usuario` INT GENERATED ALWAYS AS (),
  `Nombre` VARCHAR(45) NOT NULL,
  ` Contraseña` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Privilegio` INT NOT NULL,
  `Id Jefe` INT NULL,
  PRIMARY KEY (`Id Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manda` (
  `Id Usuario` INT NOT NULL,
  `Id Jefe` INT NOT NULL,
  PRIMARY KEY (`Id Usuario`, `Id Jefe`),
  INDEX `fk_Usuario_has_Usuario_Usuario1_idx` (`Id Jefe` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Usuario_Usuario_idx` (`Id Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario`
    FOREIGN KEY (`Id Usuario`)
    REFERENCES `mydb`.`Usuario` (`Id Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario1`
    FOREIGN KEY (`Id Jefe`)
    REFERENCES `mydb`.`Usuario` (`Id Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tareas` (
  `Id Tarea` INT GENERATED ALWAYS AS (),
  `Id Creador Tarea` INT NOT NULL,
  `Fecha Creación` DATE NOT NULL,
  `Tiempo estimado` FLOAT NOT NULL,
  `Nombre Tarea` VARCHAR(45) NOT NULL,
  `Detalles` VARCHAR(45) NULL,
  PRIMARY KEY (`Id Tarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genera` (
  `Tareas_Id Tarea` INT NOT NULL,
  `Usuario_Id Usuario` INT NOT NULL,
  PRIMARY KEY (`Tareas_Id Tarea`, `Usuario_Id Usuario`),
  INDEX `fk_Tareas_has_Usuario_Usuario1_idx` (`Usuario_Id Usuario` ASC) VISIBLE,
  INDEX `fk_Tareas_has_Usuario_Tareas1_idx` (`Tareas_Id Tarea` ASC) VISIBLE,
  CONSTRAINT `fk_Tareas_has_Usuario_Tareas1`
    FOREIGN KEY (`Tareas_Id Tarea`)
    REFERENCES `mydb`.`Tareas` (`Id Tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tareas_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Id Usuario`)
    REFERENCES `mydb`.`Usuario` (`Id Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Institución`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Institución` (
  `id Institución` INT GENERATED ALWAYS AS (),
  `Nombre Institución` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id Institución`),
  UNIQUE INDEX `Nombre Institución_UNIQUE` (`Nombre Institución` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabaja para`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabaja para` (
  `Usuario_Id Usuario` INT NOT NULL,
  `Institución_id Institución` INT NOT NULL,
  PRIMARY KEY (`Usuario_Id Usuario`, `Institución_id Institución`),
  INDEX `fk_Usuario_has_Institución_Institución1_idx` (`Institución_id Institución` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Institución_Usuario1_idx` (`Usuario_Id Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Institución_Usuario1`
    FOREIGN KEY (`Usuario_Id Usuario`)
    REFERENCES `mydb`.`Usuario` (`Id Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Institución_Institución1`
    FOREIGN KEY (`Institución_id Institución`)
    REFERENCES `mydb`.`Institución` (`id Institución`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `id Inventario` INT GENERATED ALWAYS AS (),
  `Institución_id Institución` INT NOT NULL,
  PRIMARY KEY (`id Inventario`),
  INDEX `fk_Inventario_Institución1_idx` (`Institución_id Institución` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Institución1`
    FOREIGN KEY (`Institución_id Institución`)
    REFERENCES `mydb`.`Institución` (`id Institución`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maneja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Maneja` (
  `Id Usuario` INT NOT NULL,
  `Id Inventario` INT NOT NULL,
  PRIMARY KEY (`Id Usuario`, `Id Inventario`),
  INDEX `fk_Usuario_has_Inventario_Inventario1_idx` (`Id Inventario` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Inventario_Usuario1_idx` (`Id Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Inventario_Usuario1`
    FOREIGN KEY (`Id Usuario`)
    REFERENCES `mydb`.`Usuario` (`Id Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Inventario_Inventario1`
    FOREIGN KEY (`Id Inventario`)
    REFERENCES `mydb`.`Inventario` (`id Inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Objeto` (
  `id Objeto` INT GENERATED ALWAYS AS (),
  `Id Inventario` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Descripción Avería` VARCHAR(45) NULL,
  PRIMARY KEY (`id Objeto`, `Id Inventario`),
  INDEX `fk_Objeto_Inventario1_idx` (`Id Inventario` ASC) VISIBLE,
  CONSTRAINT `fk_Objeto_Inventario1`
    FOREIGN KEY (`Id Inventario`)
    REFERENCES `mydb`.`Inventario` (`id Inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
